name: 'Pull Request Phrase'
description: 'Create a PR after the Phrase pull'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: phrase/setup-cli@v1
      with:
        version: 2.19.0
    - shell: sh
      run: |
        action.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}