name: 'Pull Request Phrase'
description: 'Create a PR after the Phrase pull'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: phrase/setup-cli@v1
      with:
        version: 2.19.0
    - shell: sh
      run: |
        PHRASE_BRANCH="phrase/update"
        git fetch
        
        echo "INFO: Getting existing branch"

        BRANCH_ALREADY_EXISTS=$(git checkout -b "$PHRASE_BRANCH" "origin/$PHRASE_BRANCH" --quiet && echo 0 || echo 1)
        
        if [ "$BRANCH_ALREADY_EXISTS" != "0" ]
        then
          echo "INFO: Branch doesn't exist on origin, check it out"
          git checkout -b "$PHRASE_BRANCH"
        fi

        phrase pull
  
        NO_CHANGES=$(git diff --quiet && echo 0 || echo 1)

        if [ "$NO_CHANGES" != "0" ]
        then
          echo "INFO: New Phrase strings to commit..."
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add --all
          git commit --message "DO-00 feat: update phrase" --no-verify
          git push origin "$PHRASE_BRANCH" --no-verify

          if [ "$BRANCH_ALREADY_EXISTS" != "0" ]
          then
            echo "INFO: Create new Pull Request..."
            gh pr create -B main -H phrase/update --title 'DO-00 feat: Update Phrase strings' --body 'Created by Github action'
          else
            echo "INFO: No need to create Pull Request"
          fi
        else
          echo "INFO: No new Phrase strings!"
        fi